/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class j2c_util_ColorBasedSimilarity */

#ifndef _Included_j2c_util_ColorBasedSimilarity
#define _Included_j2c_util_ColorBasedSimilarity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     j2c_util_ColorBasedSimilarity
 * Method:    getCBSList
 * Signature: (Ljava/util/List;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_j2c_util_ColorBasedSimilarity_getCBSList
  (JNIEnv *, jobject, jobject image_list);

#ifdef __cplusplus
}
#endif
#endif
